import Header from '@components/Header';
import Head from 'next/head';
import { FlexContainer } from './styles';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Hearty Fridge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <FlexContainer>{children}</FlexContainer>
    </>
  );
};

export default Layout;
