import Head from 'next/head';
import Image from 'next/image';
import styles from '@styles/Home.module.css';
import TestComponent from '@components/Test';
import { QueryClient, useQuery } from 'react-query';
import { callApi } from '@components/Test/api';
import { dehydrate } from 'react-query';

function Home() {
  const { isLoading, error, data } = useQuery('hello', () => callApi());
  console.log(isLoading, error, data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestComponent />
      <div style={{ textAlign: 'center', color: 'black' }}>
        {data ? data.data.name : ''}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery('hello', () => callApi());
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}

export default Home;
